server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: mysecretpassword

tmp:
  app-configuration-token: ${CAPYBARA_GITHUB_TOKEN}
