server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: mysecretpassword

dependencies:
  carbon-aware-api:
    url: ${CARBON_AWARE_API_URL:https://carbon-aware-api.azurewebsites.net}

tmp:
  app-configuration-token: ${CAPYBARA_GITHUB_TOKEN}
